### ISSUE TITLE
footer section 的 twitter 和 discord 的hovering 颜色需要更改一下

### ISSUE THREAD

**Issue by zhuyinzhuyin** [8glabs/website#3]
twitter 的hovering 是蓝色
discord 的hovering 是紫色

![image](https://user-images.githubusercontent.com/96524134/196992684-3fd9355d-2d32-4df6-bc4b-2866b690b2df.png)

**Comment by mgyong** [comment]
Twitter link = https://twitter.com/8glabs
discord link = https://discord.gg/Nskxybzbgp
email link = mailto: support@8glabs.com

**Comment by zhuyinzhuyin** [comment]
fixed
